=== Closures: Anonymous functions that can capture their Environment

Closures are anonymous functions that can be saved in a variable or passed as arguments to other functions.
They are usually short and used within a very narrow context rather than to handle an elaborate scenario.

==== Creating an abstraction of behavior with closures
To an extent Closures can be used as type of function pointer in *C/C++*.
You can for example use it to conditionally apply various algorithms upon same set of inputs.

==== Closure type inference and annotation
Closures unlike functions do not require annotation of parameters and return types.
As they are short and used in narrow context, compiler can reliably infer the data types of parameters and return.
[NOTE]
====
We impose annotation requirement on functions but not closures because functions can be exposed to others and making all data types explicit can make things clear to everyone.
However, closures are mostly local anonymous functions which are not seen by external code.
====

However, if in case programmer wants to increase the explicitness and clarity, he can annotate them.
Here are some examples:
----
fn add_one_v1(x: u32) -> u32 { x + 1 } // function
let add_one_v2 = |x: u32| -> u32 { x + 1 }; // annotated closure looks like function
let add_one_v3 = |x| { x + 1 }; // closure without type annotation
let add_one_v4 = |x|  x + 1; // for single expression closure "{}" not needed
----
[WARNING]
====
Closures are not templates meaning only one concrete type is inferred.
====
The first usage of the closure defines the concrete type that the compiler is going to infer.

Each closure instance has its own unique anonymous type i.e. even if two closures have the same signature, their types will be considered different.
In the examples above closures `add_one_v2`, `add_one_v3`, and `add_one_v4` have the same signature, but they are all considered to be of a unique different type.

==== Storing closures using generic parameters and the `Fn` traits
All closures implement at least of the `Fn`, `FnMut` or `FnOnce` traits provided by the standard library.

To store a closure in a struct, we will need to impose one of the above traits on the structure's generic parameter.

==== Capturing the environment with closures
Closures can also access the variables in the same scope that they are defined in.
The access can happen in 3 ways, same as how a function can take a parameter, and this is encoded in 3 `Fn` traits which are automatically inferred by compiler based on how the variables from the environment are used:

* `FnOnce`:
+
Consumes the variables that it captures meaning it takes the ownership of the variables used in it which belong to the same scope that it's defined in.
+
All closures implement this coz all closures can be called at least once.
* `FnMut`:
+
Mutably borrows the variables in same scope, hence it can change their value without taking over the ownership.
+
Closures that don't move captured variables also implement `FnMut`.

* `Fn`:
+
Immutably borrows the variables in the same scope, hence it cannot change the value.
+
Closures that don't mutate captured variables also implement `Fn`.

Even for a complex data type, closures do not automatically take the ownership.
They need to be forced using the keyword `move` prefixed before the closure.
[NOTE]
====
Though this might seem odd, it is useful in concurrent programming.
====

[IMPORTANT]
====
Though it looks like `move` closures can implement only `FnOnce`, they may still implement `Fn` or `FnMut` coz the traits implemented by a closure are dictated by what the closure does with captured values, not the way it captures them.
`move` just says the way closure captures the values but not what it does with them.
====

[TIP]
====
When specifying trait bounds, just use `Fn` and do your implementation.
If `FnMut` or `FnOnce` is required to execute your closure, compiler will tell you, and you can make the necessary changes.
====
