=== References and Borrowing

To regain the ownership of the shallow-copy parameter that was passed outside the function, it must be returned from the function and collected outside.
This is a bit annoying to do everytime.
So, as an alternative, to work with a variable(memory) without gaining ownership of it, a reference to the variable can be used.
[NOTE]
====
The act of creating a reference is called borrowing.
====
When a reference goes out of scope i,e, when drop function is called the memory that the reference points to is not deallocated coz the reference never owned it in the first place.

References need not necessarily be read-only.
They can be used to mutate memory iff the memory that they are referring to is declared as mutable in the first place.

To simplify memory management, rust imposes a rule:
within a particular scope only one mutable reference to a memory can exist.
This restriction prevent data corruption from race conditions which occur when a pointer reads a particular memory while another is writing to the same memory.
Since, race conditions are eliminated at compile time, there's no need for special mechanisms to synchronize the data access.

You can mix mutable reference with any number of immutable references.
To ensure that the users of immutable references won't unexpectedly have their memory changed, if immutable references are declared:

* before mutable one, compiler invalidates all the immutable ones declared before the mutable one
* after mutable one, compiler invalidates the mutable one itself

By invalidating references this way, the compiler is imposing a non-lexical lifetime(non-lexical scope) on the reference.
When a reference is used outside it's (non-lexical) scope compilation error occurs.