== An I/O Project: Building a Command Line Program

In this project we build our own version of the command line tool `grep` that interacts with file and command line io.
[NOTE]
====
`grep` stands for *g*-lobally search a *r*-egular *e*-xpression and *p*-rint.
In the simplest of the use cases, it takes as its arguments a filename and a string, reads the file, searches for the lines that contain a specified string and prints those lines.
====

[IMPORTANT]
====
*To follow this section follow the git history to follow the code evolution and the notes in the comments*
====

=== Accepting Command Line Arguments

==== Reading the argument values
`std::env::args()` is used to read the command line arguments.
It will panic if unicode values are entered.
For taking unicode input you can use `std::env::args_os`, which returns `OsString`, whose values differ based on the OS, instead of `String`.
For the sake of simplicity we choose to not deal with unicode at the moment.

==== Saving the argument values in variables
Using `collect` on `std::env::args()` turns the iterator returned by it into a vector of all the command line arguments produced by it.

=== Reading a file
`std::fs::read_to_string(file_name)` is used to read the file.
It takes in a filename, opens the file, reads its contents and returns them as `Result<String>` meaning, upon success you'll get `Ok(String)` and on failure you'll get `Err(String)`.

=== Refactoring to improve Modularity and Error Handling
[IMPORTANT]
====
Make code changes in small units and continuously execute to check for correctness.
====
[TIP]
====
On the first pass always go for the simplest implementation.
Resist the strong temptation to pre-optimize i.e. do not try to write hyper-optimized code on your first pass.
====

==== Separation of concerns for binary projects
In a binary project programmers tend to write multiple tasks within the `main` function.
As the project grows large this can be problematic.
Rust community recommends splitting your program into a `main.rs` & `lib.rs` and move your program logic to `lib.rs`

The `main` function should be limited to performing:

* Parsing command line arguments
+
[NOTE]
====
If command line parsing logic is small you can keep it in `main.rs` otherwise move it to `lib.rs`
====
* Setting up any other configuration
* Calling a `run` function in `lib.rs`
* Handling the error if `run` returns an error

This way you can test all the code that gets called from `main` function thoroughly and the code within the `main` function will be small enough to verify its correctness by just reading it.

===== Extracting the argument parser
Move the argument parsing logic in the `main` function to another function within `main.rs` or `lib.rs` depending on the length of parsing logic

===== Grouping configuration values
After parsing the arguments you can group the configuration values under a `Config` struct.
[TIP]
====
* Whenever you are returning a tuple from a function, if they are related to same function then it is meaningful to group them together under a struct

* It is ok to trade a little performance to gain code simplicity and readability.

* Don't be obsessed with primitive data types and be open to using complex data types when you can make gains in terms of code simplicity, scalability or readability.
====

===== Creating a constructor for `Config`
If all that your parsing function is doing is creating an instance of your `Config` struct, then you can delete this function and move all the logic inside it to a constructor of `Config` struct.

==== Fixing the Error Handling
After setting up the minimal working logic, move to handling errors.

===== Improving the Error message
Write your own error messages and cause panic upon errors everywhere.

===== Returning a `Result<T, E>` instead of `panic!`
Now wherever appropriate you can selectively change panics to returning `Result<T, E>`.

===== Handle `Result<T, E>`
You can use `unwrap` and similar methods to get the value upon success and error return upon failure.
[TIP]
====
Using `unwrap` means you'll need to do pattern matching, instead you can `unwrap_or_else` which behaves same as `unwrap` during success and allows you to write a code in closure upon failure.
====
Wherever you want to exit the program upon error you can use `std::process::exit`.

==== Extracting logic from `main`
Move all the post configuration program logic into a function called `run`.

===== Returning errors from `run` function
Even `run` function can handle non-panic errors by returning `Result<T, E>` to `main` function

===== Handling errors from `run` in `main`
This time you get nothing upon success but something upon failure, so you can use something like `if let` construct or `unwrap_or_else` function instead of just `unwrap` or similar functions.
But, `if let` construct is more verbose and readable in this case, you better to use that.

==== Splitting code into a library crate
Move `run` function and all its relevant functions and structs to a new `src/lib.rs` file.
Use `pub` to make the relevant code among the moved code public.
Use `use` to bring the necessary public code in `lib.rs` in scope in `main.rs`.

Now you can perform tests on your logic by directly calling the functions with various arguments and checking return values without running the binary from the command line.

=== Developing the library's functionality with TDD
TDD stands for test driven development which is a software development technique that follows these steps:

* Write a test that fails and run it to make sure it fails for the reason you expect
* Write or modify just enough code to make the new test pass
* Refactor the code you just added or changed and make sure that all the existing tests continue to pass
* Repeat

==== Writing a failing test
Write your test case and write enough library code just to make the test case compile, not to pass it.

==== Writing code to pass the test
First write your idea as a very top level pseudocode/algorithm in comments.
Then translate each line in your pseudocode to code while running the tests to make sure they continue to fail until you have worked through the whole pseudocode.

After this write more failing test cases and iteratively build the code to pass all the possible test cases

==== Integration with `run`
After you have built your function to your satisfaction, add it to your `run` method directly or indirectly through another function(s) which would call your new function.

=== Working wih Environment variables
Apart from command line arguments, we can also use environment variables to configure the behavior of our program.
Environment variables can be accessed from `std::env::var` function which returns `Result<String, VarError>` i.e. it returns value of environment variable wrapped in `Ok` if it exists otherwise returns a `Err(VarError)`.
If you just want to check existence of the environment variable without worrying about its value, it's sufficient to check if there's an error return using `is_err` function which returns `true` when there's an error and vice-versa.
If you want to get the actual value of the environment variable, then unwrap or pattern match the result to extract the value in `Ok` upon success.