=== Methods

Methods are written just like functions, but they are defined within the context of a struct(or an enum or a trait object).
Hence, methods can be used to specify the behavior that the instances of struct have.
The first parameter of a method is always `self` meaning the instance of the struct where the method is being called on.
Methods can take the struct with ownership or borrow(using reference) which can be mutable, or immutable.
Hence, the first parameter can be `self`, `&self` or `&mut self`.

A method can have the same name as a field.
This is often useful to write *getter* functions which rust doesn't provide by default unlike languages such as *C#*.

[NOTE]
====
Rust has no notion of *C* pointers, hence structs do not have an equivalent `->` operator.
Rust has references and its `.` operator automatically adds `&`, `&mut` or `*` based on the signature of the method.
Hence, rust automatically references or dereferences.
====

Just like static methods in *C++*, we have associated methods in rust which can be called without an instance of the struct.