=== Bringing paths into scope with *use* keyword

Writing paths can be repetitive and inconveniently long.
To simplify, we can bring a path into scope with *use* keyword and use the path's items as if they're local items.
The path can be absolute or relative.
This is similar to creating a symbolic link in the filesystem.
[NOTE]
====
Paths can only be brought into scope if its privacy allows you to
====

==== Creating idiomatic *use* paths
Normally a module containing several items is brought into scope, and
----
<module_name>::<item_name>
----
is used to access the item.
But, you can bring a specific item into scope with its path and use it just like you would use a local item.
This type is normally used for structs an enums.
[WARNING]
====
You cannot bring to items with same name from different paths into scope.
You can bring their parent into the scope and then use the parent name to access the item.
====

==== Providing new names with the *as* keyword
You can create an alias to a path using *as*.
[TIP]
====
Now, if you want to bring items with same name from different paths into scope, you can declare one of them with *as* statement to remove ambiguity in name resolution.
====

==== Re-exporting names with *pub* *use*
The symbolic link created is private and accessible only to the code in the current module/file.
To use it outside it, you can prefix the *use* statement with *pub*.
This is very useful to organize code while writing libraries where we write one structure and expose a different structure.

==== Using external packages
After adding the external package into the crate as a dependency in *Cargo.toml*, to actually use it in the code its code items are declared with *use* statement.
[NOTE]
====
The standard library *std* is also a crate that’s an external to our package.
Because it is shipped with the language, we don’t need to change *Cargo.toml* to include it in our package.
But, we do need to refer to it with *use* to bring its items into our package’s scope.
====

==== Using nested paths to clean-up large *use* lists
If we’re using multiple items defined in the same crate or same module, listing each item can take up a lot of vertical space in our files.
Hence, we can define just the parent and nest all its children as follows:
----
use <parent>::{<child1>, <child2>};
----
Nested paths can be used at any level
[TIP]
====
----
use <parent>::<child1>;
use <parent>::<child1>::<grandchild1>;
----
can be written as:
----
use <parent>::<child1>::{self, <grandchild1>}
----
====

==== The *glob* operator
If you want to bring all the public items defined in a path to scope, you can just do
----
use <parent>::*;
----
[WARNING]
====
Though it seems convenient, be careful in using this coz it will become difficult to tell which names belong to what when there are too many names in scope.
====
It is normally used in unit testing to bring all the public items into scope at once.